"""add is_featured and featured_order to Wiki

Revision ID: 7af4a352f656
Revises: ac0b0a40cd51
Create Date: 2026-03-05 05:41:42.069423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af4a352f656'
down_revision = 'ac0b0a40cd51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wiki', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('featured_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wiki', schema=None) as batch_op:
        batch_op.drop_column('featured_order')
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###
