"""init with naming convention

Revision ID: ac0b0a40cd51
Revises: 
Create Date: 2026-02-28 07:35:49.244140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac0b0a40cd51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_badge')
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint(batch_op.f('uq_class_name'), ['name'])

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint(batch_op.f('uq_group_name'), ['name'])

    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_tag_name'), ['name'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_student_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_student_id'), ['student_id'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])
        batch_op.drop_column('streak_days')

    with op.batch_alter_table('user_active_status', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user_badge', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_badge_serial_number'), ['serial_number'])

    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user_sticker', schema=None) as batch_op:
        batch_op.drop_column('page_number')

    with op.batch_alter_table('wiki_classes', schema=None) as batch_op:
        batch_op.alter_column('wiki_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('class_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('wiki_groups', schema=None) as batch_op:
        batch_op.alter_column('wiki_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('wiki_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('order_weight', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_wiki_page_folder_id_wiki_folder'), 'wiki_folder', ['folder_id'], ['id'])
        batch_op.drop_column('page_type')

    with op.batch_alter_table('wiki_users', schema=None) as batch_op:
        batch_op.alter_column('wiki_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wiki_users', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('wiki_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('wiki_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_type', sa.TEXT(), server_default=sa.text("'markdown'"), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_wiki_page_folder_id_wiki_folder'), type_='foreignkey')
        batch_op.drop_column('order_weight')
        batch_op.drop_column('folder_id')

    with op.batch_alter_table('wiki_groups', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('wiki_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('wiki_classes', schema=None) as batch_op:
        batch_op.alter_column('class_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('wiki_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user_sticker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_number', sa.INTEGER(), server_default=sa.text('1'), nullable=True))

    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user_badge', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_badge_serial_number'), type_='unique')

    with op.batch_alter_table('user_active_status', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak_days', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_student_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')
        batch_op.create_index(batch_op.f('idx_user_student_id'), ['student_id'], unique=1)

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_tag_name'), type_='unique')

    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_group_name'), type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_class_name'), type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    op.create_table('_alembic_tmp_badge',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=False),
    sa.Column('icon', sa.VARCHAR(length=255), nullable=False),
    sa.Column('condition_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('condition_value', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_hidden', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('start_time', sa.DATETIME(), nullable=True),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('sticker_count', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('total_limit', sa.INTEGER(), nullable=True),
    sa.Column('issued_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), server_default=sa.text("'一般'"), nullable=True),
    sa.Column('custom_condition_text', sa.VARCHAR(length=255), nullable=True),
    sa.Column('rarity', sa.VARCHAR(length=20), server_default=sa.text("'common'"), nullable=True),
    sa.Column('is_secret', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('issuer', sa.VARCHAR(length=100), server_default=sa.text("'WikiBook'"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
