"""Add VinylRecord and UserVinyl models

Revision ID: b2508e5693ab
Revises: f596eedcdeb7
Create Date: 2026-03-20 08:20:50.323279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2508e5693ab'
down_revision = 'f596eedcdeb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.alter_column('wiki_page_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_assignment_wiki_page_id_wiki_page'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_assignment_created_by_id_user'), 'user', ['created_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_assignment_created_by_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_assignment_wiki_page_id_wiki_page'), 'wiki_page', ['wiki_page_id'], ['id'])
        batch_op.alter_column('wiki_page_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
