"""empty message

Revision ID: f596eedcdeb7
Revises: 7af4a352f656
Create Date: 2026-03-07 14:57:02.220320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f596eedcdeb7'
down_revision = '7af4a352f656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmark_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=False),
    sa.Column('rarity', sa.String(length=20), nullable=True),
    sa.Column('condition_type', sa.String(length=50), nullable=False),
    sa.Column('condition_value', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookmark_types'))
    )
    op.create_table('user_bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bookmark_type_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=True),
    sa.Column('is_notified', sa.Boolean(), nullable=True),
    sa.Column('is_placed', sa.Boolean(), nullable=True),
    sa.Column('target_type', sa.String(length=20), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_url', sa.String(length=255), nullable=True),
    sa.Column('target_block_id', sa.String(length=100), nullable=True),
    sa.Column('target_title', sa.String(length=255), nullable=True),
    sa.Column('target_snippet', sa.Text(), nullable=True),
    sa.Column('placed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bookmark_type_id'], ['bookmark_types.id'], name=op.f('fk_user_bookmarks_bookmark_type_id_bookmark_types')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_bookmarks_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_bookmarks'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_bookmarks')
    op.drop_table('bookmark_types')
    # ### end Alembic commands ###
